language: node_js

env:
  - CXX=g++-4.8 # Needed to compile zmq

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libzmq3-dev

script:
  - npm run lint
  - npm test
